services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - mynetwork

  delteaching-dotnet:
    build:
      context: .
      dockerfile: delteaching-dotnet/Dockerfile
    depends_on:
      sqlserver:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=master;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork
      
networks:
  mynetwork: